version: '3'

services:

  db:
    image: postgres:latest
    volumes:
      - data-volume:/var/lib/postgresql/data
    networks:
      - db_nw
      
  flask:
    build: ./flask
    volumes:
      - //c/docker/SWE/flask/:/opt/services/flaskapp/src
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db
      
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - web_nw
    depends_on: 
      - flask

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
volumes:
  data-volume: